### ISSUE TITLE
Please update code 1.0.9 -> 1.2.0

### ISSUE THREAD

**Issue by cyberman54** [markdotai/emtb#5]
Version of current code in this repository is stated as 1.0.9 in manifest.xml, while app version in garmin iq store is listed as 1.2.0

_Initial Release: December 31, 2019
Updated: January 29, 2022
Version: 1.2.0_

Could you, please, update the source code in the repository? Thanks.

**Comment by markdotai** [comment]
Hi - just synced it :)
The branch you want is: master-release (which also currently matches master-release-1.2.0)
There is some code on the master branch (for a new layout) which I still haven't added to the app store version yet.

**Comment by cyberman54** [comment]
Thanks!
